Exit normally instead of indicating failure during `install-transpile` if the user doesn't want to replace the configuration (#1691)
# Changes
### What does this PR do?

When `install-transpile` is invoked but the user already has a
configuration file in their workspace, they are prompted:
```
Do you want to override the existing installation? (default: no):                                                                   
```

Prior to this PR, if the user chooses the default (`no`) then the
process immediately exits, signalling an error:
```
Do you want to override the existing installation? (default: no): no 
Lak `transpile` is already installed and no override has been requested. Exiting...
Error: exit status 1
17:58:08 Info: failed execution pid=727 exit_code=1 error="exit status 1"
17:58:08 Debug: no telemetry logs to upload pid=727
```

This PR updates this so that instead we gracefully exit:
```
Do you want to override the existing installation? (default: no): 
18:02:19     INFO [d.l.lakebridge.install] Installation completed successfully! Please refer to the documentation for the next steps.
Info: completed execution
```

### Relevant implementation details

The blueprint CLI support automatically converts `SystemExit` (which was
being raised before) into an error.

### Functionality

- modified existing command: `databricks labs lakebridge
install-transpile`

### Tests

- manually tested
- updated unit test